changes

diff --git a/scripts/change_display b/scripts/change_display
--- a/scripts/change_display
+++ b/scripts/change_display
@@ -137,19 +137,19 @@ function all_outputs_configured() {
 
 function environment_check() {
   if ! command -v cat &>/dev/null; then
-    echo 'You seem to be missing coreutils. You'\''re gonna have a bad time.' >&2
+    echo 'You seem to be missing coreutils. You' >&2
     exit 255
   elif ! command -v grep &>/dev/null; then
-    echo 'grep seems to be missing. You'\''re gonna have a bad time.' >&2
+    echo 'grep seems to be missing. You' >&2
     exit 255
   elif ! command -v xrandr &>/dev/null; then
-    echo "Try xrandr-dmenu without xrandr, and you're gonna have a bad time." >&2
+    echo "Try xrandr-dmenu without xrandr." >&2
     exit 255
 elif ! command -v rofi &>/dev/null; then
-    echo "Try xrandr-dmenu without dmenu, and you're gonna have a bad time." >&2
+    echo "Try xrandr-dmenu without dmenu." >&2
     exit 255
   elif ! xset q &>/dev/null; then
-    echo 'Woah there, cowboy! You need to run this from inside X!' >&2
+    echo 'Waaaaaaaaaat?! You need to run this from inside X!' >&2
     exit 1
   fi
 }
